pikvm/kvmd

- web/kvm/navbar-macro.pug
Not sure if you require an issue open especially considering how minor this is.
> minor grammar corrections

- web/kvm/index.html
- web/share/css/kvm/stream.css
- web/share/css/window.css
- web/share/js/kvm/mouse.js
- web/share/js/kvm/stream.js
- web/share/js/wm.js
> Scaling video through window resize and full screen mode

- PKGBUILD
- configs/kvmd/main/v2-hdmi-rpi3.yaml
- configs/os/boot-config/v2-hdmi-rpi3.txt
- configs/os/cmdline/v2-hdmi-rpi3.sed
- configs/os/udev/v2-hdmi-rpi3.rules
> Add v2-hdmi-rpi3 config for rpi3 model a+

- web/share/js/kvm/hid.js
Got one of the smallest pull requests ever here.
Just noticed this while messing around with the web interface.
> Fix spelling error in web interface

- web/share/js/kvm/msd.js
encode URL values to allow drive image name with special character
> Encode URL values

- PKGBUILD
- kvmd/plugins/ugpio/pwm.py
- testenv/Dockerfile
- testenv/linters/vulture-wl.py
1. Add to /boot/config.txt
```
dtoverlay=pwm
```
2. Create /etc/udev/rules.d/99-kvmd-pwm.rules
```
SUBSYSTEM=="pwm*", ACTION=="add", RUN+="/bin/chgrp -R kvmd /sys%p", RUN+="/bin/chmod -R g=u /sys%p"
SUBSYSTEM=="pwm*", ACTION=="change", ENV{TRIGGER}!="none", RUN+="/bin/chgrp -R kvmd /sys%p", RUN+="/bin/chmod -R g=u /sys%p"
```
3. Connect Servo motor like SG90 PWM connection to RPi GPIO18, +5V and GND to a 5V and GND pin on header
4. Add to /etc/kvmd/override.yaml
```
kvmd:
gpio:
drivers:
servo1:
type: pwm
pwm_chip: 0                  # PWM Chip Number
pwm_period: 20000000         # Servo Motor SG90 Period in nano-seconds
duty_cycle_push: 1500000     # Servo Motor SG90 duty_cycle for pushing button
duty_cycle_release: 1000000  # Servo Motor SG90 duty_cycle for releasing button
scheme: …
```
> Implement button push using servo motors controlled via pwm

- kvmd/plugins/ugpio/pway.py
The previous commit to this accidentally broke it. The awkwardness with this KVM switch's serial port communication is that the commands to switch the port are 1-based index (e.g. `PS 1` or `PS 15` for ports 1 or 15), but the switch reports which port is active with a 0-based index (`VGA_SWITCH_CONTROL=0` or `VGA_SWITCH_CONTROL=14`, respectively). This normalizes those indexes again.
I also adjusted the "reset" to use that method name explicitly. At the moment just sending `PS` resets the switch to port 1. The send channel method was a little confusing on that part.
> PWAY plugin fix: Normalize pin/channel index to 0-based

- web/share/css/window.css
prevents fullscreen jiggling of 1px border when toggling focus & fixes fullscreen visible round corners when focus is lost.
> fix fullscreen focus related jiggling & visible round corners

- hid/src/main.cpp
- hid/src/ps2/hid.h
- hid/src/usb/hid.h
https://github.com/pikvm/kvmd/pull/90
> change name of method getOfflineAs->isOffline to simplyfy the interface

- hid/lib/drivers/driver.h
- hid/lib/drivers/mouse.h
- hid/src/main.cpp
- hid/src/usb/hid.h
https://github.com/pikvm/kvmd/pull/90
> Driver structure

- hid/patch.py
- hid/patches/arduino-no-main.patch
- hid/src/main.cpp
I also changed way of patching libs since previous one was silent on error.
https://github.com/pikvm/kvmd/pull/90
> adds setup/loop

- kvmd/plugins/ugpio/cmd.py
I wanted to be able to use an arbitrary commands output as a gpio state. This makes it easy to script arbitrary devices/statuses for display in the ui.
> add the ability to use command exit status as a gpio state in ugpio/cmd

- hid/lib/drivers-avr/factory.cpp
- hid/lib/drivers-stm32/board-stm32.h
- hid/lib/drivers/board.h
- hid/lib/drivers/driver.h
- hid/lib/drivers/factory.h
- hid/src/main.cpp
reset PIN on kvmd is optional. HID works without problem until _reset_required is set. After that device has to be restarted manually. With SW reset it is possible to switch between HID without reset PIN.
https://github.com/pikvm/kvmd/pull/90
> add SW reset

- testenv/linters/pylint.ini
- testenv/tox.ini
These items are called out as inactive or removed from pylint.
> Remove unused items

- web/kvm/index.html
- web/kvm/navbar-system.pug
- web/share/js/kvm/mouse.js
Allows scrolling slider from 1-100 lines.
> Add scroll rate slider, with proper pug support

- kvmd/plugins/ugpio/extron.py
This adds support for various Extron USB and VGA switchers (possible other Extron switchers given how both USB and VGA share the same serial API).
I was hesitant to open this PR due to being niche, but figured it's a good place for conversation.
> Add plugin for Extron USB and SW VGA switchers

- kvmd/apps/vnc/rfb/__init__.py
fix https://github.com/pikvm/pikvm/issues/1349
> fix vnc security type handshake for rfb version 3

- hid/pico/Makefile
I hope this fixes the testsuit error: https://github.com/No0ne/ps2x2pico/commit/404aaf02949d5bee8013e3b5d0b3239abf6e13bd#diff-2764af3dfc8be81b7195cc68cfc549612b7c3dff1c5d1db621d4c224428b9253R425
> fix testsuit error

- hid/arduino/Makefile
- hid/arduino/avrdude-rpi.conf
- hid/arduino/platformio-avr.ini
> hid: fix flashing hid using avrdude 8.0

- web/index.pug
> Update copyright years in index.pug
