pikvm/kvmd

kvmd/apps/kvmd/api/info.py, kvmd/apps/kvmd/http.py
Prometheus https://prometheus.io/ is one of the popular monitoring systems. It pulls service's endpoint to get metrics in a simple text format https://prometheus.io/docs/instrumenting/exposition_formats/
Existing InfoApi was used as it already collecting and exposing system info. There is no sensitive information in it, so, could be exposed w/o auth.
In order to enable Prometheus getting metrics from pikvm following config could be used:
```
scrape_configs:
- job_name: "pikvm"
metrics_path: "/api/export/prometheus/metrics"
static_configs:
- targets: ["pikvm:8080"]
```
I've tested it using `make run` and Prometheus server and it works fine. Here is a sample output of `/api/metrics`:
```
pikvm_temp_cpu 36.511
pikvm_temp_gpu 35.0
pikvm_throttling_raw_flags 0
pikvm_throttling_undervoltage_now …
```
=> Add minimal prometheus exporter support

kvmd/aiotools.py, kvmd/apps/kvmd/api/auth.py, kvmd/apps/kvmd/api/streamer.py, kvmd/apps/kvmd/http.py, kvmd/apps/kvmd/info/hw.py, kvmd/apps/kvmd/server.py, kvmd/apps/vnc/rfb/__init__.py, kvmd/apps/vnc/server.py, kvmd/keyboard/keysym.py, setup.py
Using new features provided by Python 3.8 is nice, but there are popular Linux distributions (like Debian / Raspbian) that still use Python 3.7.
Only two 3.8-specific features are used in KVMD:
* assignment expressions using `:=` operator,
* `{variable=}` substitution in f-strings.
This set of changes makes KVMD compatible with Python 3.7 by rewriting its code to not use these features. I tried to do it carefully, without sacrificing readability.
I've tested these changes thoroughly. I have KVMD with these changes working flawlessly on Raspberry Pi 4 with Raspbian.
=> Make KVMD compatible with Python 3.7

kvmd/plugins/atx/gpio.py, kvmd/plugins/hid/serial.py, kvmd/plugins/msd/relay.py, kvmd/plugins/ugpio/gpio.py
The singular `default_val` argument of `gpiod.Line.request()` method was introduced in libgpiod 1.3.
For older versions of libgpiod, `defailt_vals` argument with list value should be used.
This argument is available in newer versions of libgpiod as well for compatibility.
This change is needed for Debian / Raspbian 10 that have libgpiod 1.2.
=> Make kvmd compatible with libgpiod 1.2

hid/src/ps2/keymap.h, hid/src/usb/keymap.h, keymap.csv, kvmd/keyboard/mappings.py, web/kvm/index.html, web/kvm/window-keyboard.pug
Some non us keyboards use an extra key for less, greater and bar (German).
I've added a blank key to the virtual keyboard since i don't know if this key represents anything on a us keyboard.
Tested with otg, hid-usb and hid-ps2
=> Added missing key on non us keyboards

genmap.py, keymap.csv, kvmd/keyboard/mappings.py
AltGr(same as AltRight on us keyboard) on german keyboard is used as 3rd level shift.
=> Added mapping for AltGr key

.gitignore
venv is default suggestion from pycharm to use with this project
=> Exclude venv from project root

web/share/js/kvm/atx.js, web/share/js/kvm/gpio.js, web/share/js/kvm/hid.js, web/share/js/kvm/session.js
Came across a few more spelling errors in the web interface and fixed them.
Also updated the paste dialog to change depending on whether there's 1 or 0,2+ characters.
Also disabled the warning dialog when leaving the page if an unexpected logout has occurred. It was a little annoying to me when I was messing with my build and kept restarting the server which showed the prompt but still had the browser warning.
=> More web interface spelling fixes + a little improvement

configs/nginx/nginx.conf
nginx only binds an IPv4 socket, if the listen option is specified
without [::]. There are two possibilites to fix this issue.
Either the listen option can be specified using only [::], and
additionally including ipv6only=off. This makes nginx bind an IPv6
socket which is also able to handle IPv4 connections.
Or the listen option can be specified twice, one with [::] and one
without. This makes nginx bind two independent sockets.
If the first option is chosen, IPv4 addresses are mapped into the IPv6
address space, which might break scripts, filters, etc.
So, for now, the second option is chosen.
=> Make kvmd webui available via IPv6

PKGBUILD
It appears that using quotes when doing brace expansion doesn't work as expected:
[root@pikvm-zerow tmp]# mkdir -p -v "./etc/kvmd/{nginx,vnc}/ssl"
mkdir: created directory './etc'
mkdir: created directory './etc/kvmd'
mkdir: created directory './etc/kvmd/{nginx,vnc}'
mkdir: created directory './etc/kvmd/{nginx,vnc}/ssl'
I believe the desired behavior is the following:
[root@pikvm-zerow tmp]# mkdir -p -v "./etc/kvmd/"{nginx,vnc}"/ssl"
mkdir: created directory './etc/kvmd/nginx'
mkdir: created directory './etc/kvmd/nginx/ssl'
mkdir: created directory './etc/kvmd/vnc'
mkdir: created directory './etc/kvmd/vnc/ssl'
I think the same change would also need to be made to https://github.com/pikvm/packages/blob/master/packages/kvmd/PKGBUILD which I can update if this is acceptable.
This proposed …
=> Fix /etc/kvmd/{nginx,vnc}/ssl directory creation

kvmd/plugins/ugpio/tesmart.py
Adding support for TESMART switch.
Works over network protocol only via socket connections. Supports setting IP address and port from override.yaml.
Will send parallel documentation patch to pikvm/pikvm.
=> Plugin support for TESMART switch - tesmart.py

kvmd/plugins/ugpio/tesmart.py
Minor changes in tesmart.py testing on switch:
* Was getting an error that only a 0 timeout is allowed on transport sockets -- also I think making it 0 makes it non-blocking
* Made everything 0 based -- was only accepting ports 1-15 as written. I think this deserves some consideration, as it is confusing to create your override.yaml file saying that what you have in HDMI switch 5 needs to be configured as pin 4.
* When 0 based, you need to add 1 to the write command -- the tesmart "API" is zero based on read and 1 based on write. It was subtracting 1 on write, which is never correct.
=> fix socket timeout/zero based issues in tesmart

kvmd/plugins/ugpio/servo.py
/etc/kvmd/override.yaml
```
kvmd:
gpio:
drivers:
servo1:
type: servo
chip: 0                  # PWM Chip Number
period: 20000000         # Servo Motor SG90 Period in nano-seconds
duty_cycle_min: 350000   # Servo Motor SG90 duty_cycle for -90 degrees
duty_cycle_max: 2350000  # Servo Motor SG90 duty_cycle for +90 degrees
angle_max: 90            # Servo Motor SG90 angle at duty_cycle_max
angle_min: -90           # Servo Motor SG90 angle at duty_cycle_min
angle_push: 45           # Servo Motor SG90 angle to push button
angle_release: 20        # Servo Motor SG90 angle to release button
scheme:
short_press:
driver: servo1
pin: 0                       # Pin number is the PWM channel number on the PWM Chip
mode: output
switch: false
pulse:
delay: 0.5
max_delay: 2
long_press:
driver: servo1
pin: …
```
=> Implement servo angles

web/kvm/navbar-shortcuts.pug
Provide a helpful tooltip of what that SysRq shortcut does. As most people don't often (if ever) use SysRq keys, this will be a handy quick reference. Further details can still be gathered from the linked kernel.org article.
=> Add tooltips to SysRq shortcuts

kvmd/plugins/ugpio/xh_hk4401.py
Adds support for the "XH-HK4401" HDMI/USB KVM (e.g: https://www.aliexpress.com/item/1005002857996898.html?spm=a2g0o.productlist.0.0.4848c2c8M4keuc&algo_pvid=f1b52ddf-b577-4d45-bd56-0ad71ba4c5ba&algo_exp_id=f1b52ddf-b577-4d45-bd56-0ad71ba4c5ba-11&pdp_ext_f=%7B%22sku_id%22%3A%2212000023066118566%22%7D)
Requires inverters or a UART adapter that can do signal inversion to work. I will follow this up with a documentation PR to the main PiKVM repo to explain the setup.
=> Added driver for xh_hk4401 4 port HDMI/USB KVM

web/index.html, web/index.pug, web/share/css/index/index.css
this will hide the message when the app is running in the standalone mode being recommended
=> only show keyboard message on homepage when relevant

kvmd/apps/otg/__init__.py
Changing rndis driver configuration in override.yaml and then calling kvmd-net stop results in an error since path os_desc/c.1 is still present, but is not removed.
=> Make kvmd-net start/stop work without error while changing configuration

kvmd/apps/otg/__init__.py, kvmd/apps/otgnet/__init__.py, kvmd/validators/hw.py
rndis5 can by used with Windows XP and later. 
Manual driver installation is required. https://github.com/mfunkey/pikvm/blob/usbeth/docs/driver/win/pikvm-rndis5.inf
=> RNDIS Version 5 for Windows XP, automatic driver load on Windows using ncm

configs/os/services/kvmd-nginx.service
Currently, a `systemctl reload kvmd-nginx` fails:
```
[root@pikvm kvmd-webterm]# systemctl reload kvmd-nginx
Job for kvmd-nginx.service failed.
See "systemctl status kvmd-nginx.service" and "journalctl -xeu kvmd-nginx.service" for details.
[root@pikvm kvmd-webterm]# systemctl status kvmd-nginx
* kvmd-nginx.service - PiKVM - HTTP entrypoint
Loaded: loaded (/usr/lib/systemd/system/kvmd-nginx.service; enabled; vendor preset: disabled)
Active: active (running) since Sun 2022-03-20 21:49:29 MSK; 7h ago
Process: 17967 ExecReload=/usr/sbin/nginx -s reload -p /etc/kvmd/nginx -c /etc/kvmd/nginx/nginx.conf (code=exited, status=1/FAILURE)
Main PID: 425 (nginx)
Tasks: 6 (limit: 4915)
CPU: 6.411s
CGroup: /system.slice/kvmd-nginx.service
|-  425 "nginx: master process /usr/sbin/nginx -p /etc/kvmd/nginx …
```
=> Fix kvmd-nginx reload.

web/share/css/kvm/stream.css
fix video pixel-imperfection by taking out 1px worth of internal padding, which inadvertently causing video stream resolution to swell at default(native) resolution
fixes [https://github.com/pikvm/pikvm/issues/599](url)
=> fix video pixel-imperfection

hid/lib/drivers/keyboard.h, hid/src/main.cpp, hid/src/ps2/hid.h, hid/src/usb/hid.h
It break abstraction between driver and protocol.
The driver type (win98 fix) is part of protocol anyway so I decided to do it that way.
Driver dependent part of PROTO could be put in separate file.
It would make PROTO less clean so I don't want to do that.
Part of https://github.com/pikvm/kvmd/pull/90
=> Change name to simplify interface getLedsAs->getLeds.

kvmd/plugins/ugpio/tesmart.py
Getting started:
- disable Linux serial console and debugging in /boot/cmdline.txt as mentioned in https://docs.pikvm.org/v3/#io-ports-and-jumpers in the orange box under UART
- prepare a console to TESmart cable, it's basically ethernet pins 4,5 from the middle of RJ-45 to the TESmart connector middle, and TXD, RXD lines according to any RJ45 Cisco cable pinout diagram (and the reverse after the first attempt fails)
- https://docs.pikvm.org/tesmart/#adding-ui-elements-to-control-the-kvm-switch - add new parameters to the driver:
```yaml
mode: 2 #RS-232
device: /dev/ttyAMA0
speed: 9600
```
Things to note (or change, feedback appreciated):
1. Changed pin numbers to go from 1 to 16 (for the largest model). The TESmart protocol, both TCP/IP and RS-232, and labels on the device itself, all …
=> Support for driving TESmart KVMs by RS-232

kvmd/apps/kvmd/tesseract.py
Before analyzing the OCR text, Greyscale the image, zoom it to 2x size, and run a bicubic interpolation (4x4 anti-aliasing for upsampling).  This makes it easier for Tesseract to read the text.
=> Zoom and Enhance before running OCR

configs/nginx/nginx.conf, configs/nginx/redirect-to-https.conf
This PR makes nginx serve ACME challenges from port 80, without redirecting to HTTPS. Redirect to HTTPS is pointless (HTTPS doesn't add anything).
It also prevents obtaining keys for machines without public IP, but connected over wireguard (or other VPN) to a machine with public IP, and with public DNS pointing to the public proxy, not to the real pikvm in the intranet. For me this is a preferred mechanism since it avoids disseminating DNS keys to all machines.
=> nginx: serve ACME challenges over unencrypted HTTP

kvmd/plugins/ugpio/anelpwr.py
This add support for[ Anel NET-PwrCtrl ADV 8x ](https://de.anel.eu/?src=produkte/home/home.htm)switchable sockets as GPIO driver.
=> add support for Anel NET-PwrCtrl ADV as GPIO

scripts/kvmd-certbot
Second pull request for this bug. Apparently, in bash `cp -a <dir>/*` ignores dotfiles, which are often how authfiles get named, notably as per the documentation for SSL cert management for certbot plugins in the PiKVM Wiki. Using `cp -a <dir>/.` instead should catch dotfiles and all files and subdirectories correctly.
=> Update kvmd-certbot: fix cp -a to catch dotfiles

web/share/js/kvm/main.js
Within main, exists a `window.beforeunload` handler which brings up the "Are you sure you want to close PiKVM session?" message.   When the page is refreshed, the event is `undefined` and, the code which sets the `event.returnValue` to the aforementioned text provides an exception.  
To reproduce:
1. Open KVMD web
2. Open developer tools to view Console.
3. Interact with the page by clicking the main window.
4. Refresh the page
5. Observe type error in console. 
This patch checks if the event is defined before attempting to set the `event.returnValue`.  Other functions are maintained.
=> Fix crash on unload

kvmd/apps/__init__.py, kvmd/tools.py, kvmd/yamlconf/loader.py, kvmd/yamlconf/merger.py, testenv/tests/yamlconf/test_merger.py
Hello team,
This Pull Request encapsulates a significant refactor of the existing merge method that was previously housed within the general-purpose Tools class. I have transferred this method into a new, standalone class called Merger (stored in the merger.py file), and adapted it to leverage the yaml_merge method. The original method is now called _merger and is effectively encapsulated within the new class.
Notably, this refactor has been conducted without any changes to the existing functionalities, ensuring that the new implementation is a drop-in replacement. The reason behind this move is to enhance the modularity of our codebase and allow better reusability and isolation of the merging functionalities.
To validate and verify the correctness of the new implementation, I have added …
=> Refactoring merge Method into a New Class & Adding Unit Tests

web/login/index.html
Fixes user login on iDevices by disabling capitalization on the username input field on the login homepage.
=> Turn off auto capitalize on the username input field

configs/kvmd/main/v2-hdmi-rpi3.yaml
Seems that v2-hdmi-rpi3 lost h264 support from v1 somehow.
Tested h264 support on v2 with rpi3a+
=> [v2-hdmi-rpi3.yaml] add h264 sink from v1

scripts/kvmd-udev-hdmiusb-check
Adds support for the following new revision of the board:
```bash
Raspberry Pi 4 Model B Rev 1.5
```
Without this, `/dev/video19` from the `rpivid_hevc` driver gets incorrectly linked to `/dev/kvmd-video`
```bash
[root@pikvm ~]# v4l2-ctl --list-dev
rpivid (platform:rpivid):
/dev/video19
/dev/media0
```
```bash
lrwxrwxrwx 1 root root 6 Sep 28 08:14 /dev/kvmd-video -> video19
```
=> kvmd-udev-hdmiusb-check: Add support for rPi4 b rev 1.5

kvmd/plugins/ugpio/unifi.py
Adds a GPIO driver for Unifi devices that can control POE state.
- pikvm/pikvm#1212
Configuration for the driver is as follows:
```yaml
kvmd:
gpio:
drivers:
unifi:
type: unifi
host: https://10.0.0.1:443
user: admin
passwd: admin
mac: ff:ff:ff:ff:ff:f1
verify: false
scheme:
server1_power:
driver: unifi
pin: 0
mode: output
server1_cycle:
driver: unifi
pin: 0:cycle
mode: output
switch: false
view:
table:
- ["Unifi Controller"]
- []
- ["#Server 1", "server1_power", "server1_cycle|Reset"]
```
=> Add Unifi GPIO driver

hid/pico/CMakeLists.txt, hid/pico/Makefile
This fixes two bugs regarding ghost mouse movement and key presses mentioned here: https://github.com/No0ne/ps2x2pico/issues/19
The default 10ms polling rate could be a bit too much for some systems.
Thats why I still need to implement the mouse decoupling mentioned here: https://github.com/No0ne/ps2x2pico/issues/1#issuecomment-1849435280
=> Keyboard Issues #19 fix (https://github.com/No0ne/ps2x2pico/issues/19)

kvmd/plugins/hid/__init__.py
related to https://github.com/pikvm/pikvm/issues/1301
Try adding jiggler_interval as a parameter so that it can be set in the config file. The default is 60 to keep existing behavior.
=> add parameter for mouse jiggler interval

kvmd/apps/kvmd/__init__.py, kvmd/apps/otg/__init__.py, kvmd/plugins/hid/multi.py
This introduces the ability to have different HID plugins acting as the keyboard and mouse respectively via a `multi` plugin that dispatches to the correct HID plugin. 
This properly resolves pikvm/pikvm#1291
=> Introduce multi type HID

hid/pico/Makefile, hid/pico/src/CMakeLists.txt
Please also merge this to the master branch.
It contains multiple bugfixes and scancode set 3 support for e.g. Silicon Graphics workstations.
Afterwards I'll continue with PS/2 passthru support.
=> bump to ps2x2pico-1.1

web/share/site.webmanifest
Filling in the name and adding start_url will make browsers offer to install PiKVM as an application, including adding shortcuts to the start menu and everything. This runs it in app mode just like the instructions for running chrome with the --app flag.
Requires a valid SSL certificate be setup before browsers will show the option.
=> Proper manifest file for app mode

hid/pico/Makefile, hid/pico/src/CMakeLists.txt, hid/pico/src/ph_ps2.c, hid/pico/src/ph_ps2.h
I'm still implementing this: https://github.com/pikvm/pikvm/issues/476
keyboard and mouse passthru should work :)
keyboard GPIOs are 26=data and 27=clock
mouse GPIOs are 16=data and 17=clock
=> ps2: keyboard+mouse passthru support

kvmd/apps/kvmd/sysunit.py
I got some strange dbus/systemd related exceptions when loading the landing page:
```
root                             ERROR --- add match request failed. match="sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',path='/org/freedesktop/DBus',member='NameOwnerChanged'", [Errno 32] Broken pipe
root                           WARNING --- a message handler threw an exception on shutdown
Traceback (most recent call last):
File "/home/czo/opt/venv-312/pikvm/lib64/python3.12/site-packages/dbus_next/aio/message_bus.py", line 63, in write_callback
self.offset += self.sock.send(self.buf[self.offset:])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```
=> silence the systemd/dbus exception if there are no matching services

web/share/js/kvm/atx.js, web/share/js/kvm/switch.js
=> Fix typo in switch warning pop up

web/login/index.html, web/login/index.pug
Since 2FA codes are always changing, it is not helpful to have autocomplete suggestions for this field. It just displays a long list of outdated codes.
With the html attribute `autocomplete` this behaviour can be disabled. In my opinion that is always desired for the 2fa input.
=> web: disable autocomplete for 2fa
